// =====================WARNING=====================
// This file was generated by the
// DAP..ContractGenerator
// Take care when making manual file modifications.
// =================================================

using System.ComponentModel.DataAnnotations;

namespace DAP.SqlNotebook.Contract.Entities
{
    public class ConnectionsResponse
    {
        [Required]
        public required System.Collections.Generic.ICollection<ConnectionInfo> Connections { get; set; } = null!;
    }
}