// =====================WARNING=====================
// This file was generated by the
// DAP..ContractGenerator
// Take care when making manual file modifications.
// =================================================

using System.ComponentModel.DataAnnotations;

namespace DAP.SqlNotebook.Contract.Entities
{
    public class ConnectionInfo
    {
        public required int Id { get; set; } = default!;

        [Required(AllowEmptyStrings = true)]
        public required string Name { get; set; } = default!;
    }
}