// =====================WARNING=====================
// This file was generated by the
// DAP..ContractGenerator
// Take care when making manual file modifications.
// =================================================

using System.ComponentModel.DataAnnotations;

namespace DAP.SqlNotebook.Contract.Entities
{
    public class ConnectionExecutionRequest
    {
        [Required(AllowEmptyStrings = true)]
        public required string Query { get; set; } = default!;

        /// <summary>Command timeout in seconds. If null, server default is used (e.g. 30).</summary>
        public int? CommandTimeoutSeconds { get; set; }

        /// <summary>Catalog node Id (database/source) to run the query against. If null, default app connection is used.</summary>
        public Guid? CatalogNodeId { get; set; }
    }
}