// =====================WARNING=====================
// This file was generated by the
// Take care when making manual file modifications.
// =================================================

using System.ComponentModel.DataAnnotations;

namespace DAP.SqlNotebook.Contract.Entities
{
    public class ExecutionResultRowInfo
    {
        [Required]
        public required System.Collections.Generic.ICollection<string> Values { get; set; } = null!;
    }
}