// =====================WARNING=====================
// This file was generated by the
// DAP..ContractGenerator
// Take care when making manual file modifications.
// =================================================

using System.Runtime.Serialization;

namespace DAP.SqlNotebook.Contract.Entities
{
    /// <summary>Тип ноутбука: с подключением к БД или без (Generic).</summary>
    public enum NotebookTypeInfo
    {
        [EnumMember(Value = @"Db")]
        Db = 0,

        [EnumMember(Value = @"Generic")]
        Generic = 1,
    }
}
