// =====================WARNING=====================
// This file was generated by the
// DAP..ContractGenerator
// Take care when making manual file modifications.
// =================================================

using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace DAP.SqlNotebook.Contract.Entities
{
    public class NotebookInfo
    {
        [Required(AllowEmptyStrings = true)]
        public required Guid Id { get; set; } = default!;

        [Required(AllowEmptyStrings = true)]
        public required string Name { get; set; } = default!;

        [Required]
        public required System.Collections.Generic.ICollection<NotebookCellInfo> Cells { get; set; } = null!;

        /// <summary>Optional workspace this notebook belongs to.</summary>
        public Guid? WorkspaceId { get; set; }

        /// <summary>Default database (catalog node) for this notebook.</summary>
        public Guid? CatalogNodeId { get; set; }

        /// <summary>Display name of the default database for the UI.</summary>
        public string? CatalogNodeDisplayName { get; set; }

        /// <summary>Тип ноутбука: БД (с запросами к выбранной БД) или Generic (без подключения к БД).</summary>
        public NotebookTypeInfo NotebookType { get; set; } = NotebookTypeInfo.Db;

        /// <summary>Status: Active, Archived, or Trash.</summary>
        [JsonConverter(typeof(JsonStringEnumConverter))]
        public NotebookStatusInfo Status { get; set; } = NotebookStatusInfo.Active;

        /// <summary>Optional tags.</summary>
        public List<string>? Tags { get; set; }

        public string? CreatedBy { get; set; }
        public string? UpdatedBy { get; set; }
    }
}