// =====================WARNING=====================
// This file was generated by the
// DAP..ContractGenerator
// Take care when making manual file modifications.
// =================================================

using System.ComponentModel.DataAnnotations;

namespace DAP.SqlNotebook.Contract.Entities
{
    public class NotebooksResponse
    {
        [Required]
        public required System.Collections.Generic.ICollection<NotebookMetaInfo> Notebooks { get; set; } = null!;

        public int TotalCount { get; set; }
    }
}