// =====================WARNING=====================
// This file was generated by the

// Take care when making manual file modifications.
// =================================================

using System.Text.Json.Serialization;

namespace DAP.SqlNotebook.Contract.Entities
{
    public class NotebookCellExecutionResultInfo
    {
        [JsonConverter(typeof(JsonStringEnumConverter))]
        public NotebookCellExecutionStatusInfo? Status { get; set; } = default!;

        public ExecutionResultColumnInfo[]? Columns { get; set; } = default!;

        public ExecutionResultRowInfo[]? Rows { get; set; } = default!;

        public string? Error { get; set; } = default!;

        /// <summary>For Chart cells: "line", "bar", "pie", "table".</summary>
        public string? ChartType { get; set; }
    }
}