// =====================WARNING=====================
// This file was generated by the
// DAP..ContractGenerator
// Take care when making manual file modifications.
// =================================================

using System.Runtime.Serialization;

namespace DAP.SqlNotebook.Contract.Entities
{
    public enum NotebookCellTypeInfo
    {
        [EnumMember(Value = @"Sql")]
        Sql = 0,

        [EnumMember(Value = @"Markdown")]
        Markdown = 1,

        [EnumMember(Value = @"Chart")]
        Chart = 2,

        [EnumMember(Value = @"Excalidraw")]
        Excalidraw = 3,

        [EnumMember(Value = @"Mermaid")]
        Mermaid = 4,
    }
}