// =====================WARNING=====================
// This file was generated by the
// DAP..ContractGenerator
// Take care when making manual file modifications.
// =================================================

using System.ComponentModel.DataAnnotations;

namespace DAP.SqlNotebook.Contract.Entities
{
    public class NotebookMetaInfo
    {
        [Required(AllowEmptyStrings = true)]
        public required Guid Id { get; set; } = default!;

        [Required(AllowEmptyStrings = true)]
        public required string Name { get; set; } = default!;

        /// <summary>Id of the workspace this notebook belongs to; null if not in a workspace.</summary>
        public Guid? WorkspaceId { get; set; }

        /// <summary>Тип ноутбука: БД или Generic.</summary>
        public NotebookTypeInfo NotebookType { get; set; } = NotebookTypeInfo.Db;

        public string? CreatedBy { get; set; }
        public string? UpdatedBy { get; set; }
    }
}