// =====================WARNING=====================
// This file was generated by the
// DAP..ContractGenerator
// Take care when making manual file modifications.
// =================================================

using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace DAP.SqlNotebook.Contract.Entities
{
    public class NotebookCellInfo
    {
        public required int Id { get; set; } = default!;

        [Required(AllowEmptyStrings = true)]
        [JsonConverter(typeof(JsonStringEnumConverter))]
        public required NotebookCellTypeInfo Type { get; set; } = default!;

        [Required(AllowEmptyStrings = true)]
        public required string Content { get; set; } = default!;

        [Required]
        public required NotebookCellExecutionResultInfo ExecutionResult { get; set; } = null!;

        public string? CreatedBy { get; set; }

        /// <summary>Optional human-friendly title for TOC.</summary>
        public string? Title { get; set; }

        /// <summary>Database (catalog node) used when this cell was executed.</summary>
        public Guid? CatalogNodeId { get; set; }

        /// <summary>Display name of the database for the UI.</summary>
        public string? DatabaseDisplayName { get; set; }
    }
}