// =====================WARNING=====================
// This file was generated by the
// DAP..ContractGenerator
// Take care when making manual file modifications.
// =================================================

using System.Runtime.Serialization;

namespace DAP.SqlNotebook.Contract.Entities
{
    public enum SortOrderInfo
    {
        [EnumMember(Value = @"Asc")]
        Asc = 0,

        [EnumMember(Value = @"Desc")]
        Desc = 1,
    }
}