// =====================WARNING=====================
// This file was generated by the
// DAP..ContractGenerator
// Take care when making manual file modifications.
// =================================================

using System.Runtime.Serialization;

namespace DAP.SqlNotebook.Contract.Entities
{
    public enum NotebookCellExecutionStatusInfo
    {
        [EnumMember(Value = @"Success")]
        Success = 0,

        [EnumMember(Value = @"Failed")]
        Failed = 1,
    }
}